#!/bin/sh                                                                                       
PID="org.webosinternals.gstcodecs.gsmwav"
GSMLIB="binaries/libgsm.a"
GSTGSMLIB="binaries/libgstgsm.so"
LIBINSTALL="/usr/lib"
GSTLIBSYM="/usr/lib/gstreamer-0.10/gstlibgsm-webosinternals.so"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Symlink binary
ln -s $IPKG_OFFLINE_ROOT/$PID/$GSTGSMLIB $GSTLIBSYM

# Register binary

gst-inspect

exit 0

