#!/bin/sh                                                                                       
PID="org.webosinternals.gstcodecs.gsmwav"
GSTGSMLIB="binaries/libgstgsm.so"
GSTLIBSYM="/usr/lib/gstreamer-0.10/gstlibgsm-webosinternals.so"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Symlink binary
rm -f $GSTLIBSYM
ln -s $IPKG_OFFLINE_ROOT/usr/palm/applications/$PID/$GSTGSMLIB $GSTLIBSYM

# Register binary

gst-inspect

exit 0

