#!/bin/sh                                                                                       
PID="org.webosinternals.gstcodecs.gsmwav"
GSMLIB="binaries/libgsm.a"
GSTGSMLIB="binaries/libgstgsm.so"
LIBINSTALL="/usr/local/"
GSTLIBINSTALL="/usr/local/gstreamer-0.10/"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Install binaries 
cp $IPKG_OFFLINE_ROOT/$PID/$GSMLIB $LIBINSTALL
cp $IPKG_OFFLINE_ROOT/$PID/$GSTGSMLIB $GSTLIBINSTALL

# Register binaries

gst-inspect

exit 0

