#!/bin/sh                                                                                       
GSTLIBSYM="/usr/lib/gstreamer-0.10/libgstgsm-webosinternals.so"

# Uninstall binaries
rm -f $GSTLINSYM

# Unregister binaries
gst-inspect

exit 0

