#!/bin/sh                                                                                       
GSTGSMSYM="libgstgsm-webosinternals.so"
GSTLIBINSTALL="/usr/lib/gstreamer-0.10/"

# Uninstall binaries
rm -f $GSTLIBINSTALL/$GSTGSMSYM

# Unregister binaries
gst-inspect

exit 0

