#!/bin/sh                                                                                       
GSMLIB="libgsm.a"
GSTGSMSYM="libgstgsm-webosinternals.so"
LIBINSTALL="/usr/local/"
GSTLIBINSTALL="/usr/lib/gstreamer-0.10/"

# Uninstall binaries
rm -f $GSTLIBINSTALL/$GSTGSMLIB

# Unregister binaries
gst-inspect

exit 0

